### ISSUE TITLE
Personal Details Page

### ISSUE THREAD

**Issue by vineeth-pappu** [vineeth-pappu/SexID#18]
![Personal Data](https://user-images.githubusercontent.com/17177113/148679638-f36e8f13-7900-4e5c-958d-9b19baea6142.png)

**Comment by vineeth-pappu** [comment]
One edit for all inputs ?????

**Comment by ofigenchik** [comment]
Please elaborate on. What do you mean by one edit?

**Comment by ofigenchik** [comment]
I think I got it. When Edit is clicked, I think yes, all the fields become editable. Or how do u think?

**Comment by vineeth-pappu** [comment]
> I think I got it. When Edit is clicked, I think yes, all the fields become editable. Or how do u think?

Yes making all inputs editable at once is preferable.. orlese we need to open new page for every item..

as per design its new page for every input

**Comment by vineeth-pappu** [comment]
I see having one edit button for all seems to be better.
Basically there will be 2 screens,
 1. View screen
 2. Update screen

From update screen user can edit/modify any of the saved data.

We can apply the same principle for Appearance and Service page also.
